# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @useDynLib oXim
cumsumCol <- function(data, colSums) {
    .Call('oXim_cumsumCol', PACKAGE = 'oXim', data, colSums)
}

#' @importFrom Rcpp evalCpp
#' @useDynLib oXim
ordfiltInC <- function(data, x, weightedMatrix) {
    .Call('oXim_ordfiltInC', PACKAGE = 'oXim', data, x, weightedMatrix)
}

