# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param data Echogram as matrix of numeric values.
#' @param x radius.
#' @param weightedMatrix Matrix used to filtering echogram.
#' @importFrom Rcpp evalCpp
.ordfilt2_C_internal <- function(data, x, weightedMatrix) {
    .Call('oXim_ordfilt2_C_internal', PACKAGE = 'oXim', data, x, weightedMatrix)
}

